name: N1 - Execução manual
# Gatilhos de execução exigidos
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: # Execução manual
  
jobs:
  test-automation:
    runs-on: ubuntu-latest

    steps:
      #clone do projeto
          - uses: actions/checkout@v5

          #passo a passo do node 
          - uses: actions/setup-node@v5
            with:
             node-version: 24.x

          #instalação do yarn 
          - name: instalando Yarn 
            run: npm install -g yarn 


          #instalação das dependencias 
          - name: instalando dependencias
            run: yarn

          # instalação o mocha 
          - name: instalando o mocha
            run: yarn add mocha --dev

          # execução dos testes e2e 
          - name: Executando testes e2e 
            env:
                BASE_URL: 'https://jessicaemg.github.io/projeto-livro-aula05'
            run: yarn run e2e

          # Salvando o relatório que o seu comando gerou na pasta mochawesome-report
          - name: Salvando o Relatório do Mochawesome
            uses: actions/upload-artifact@v5
            if: always() # Salva mesmo se o teste falhar
            with:
             name: relatorio-livros-mocha
             path: mochawesome-report/
             retention-days: 30

          # 2. NOVO: Captura e armazena os arquivos do relatório na pipeline
          - name: Armazenando o Relatório do Mochawesome
            uses: actions/upload-artifact@v5
            if: always() 
            with:
              name: relatorio-livros-mocha-${{ github.run_attempt }}      
              path: mochawesome-report/       
              retention-days: 30              